### PR TITLE
4.2.0.4

### PR DESCRIPTION
**Pull request by bmcstdio**

### CODE REVIEW

**Comment by bmcstdio** [comment]
@volmarl can we expect this to be merged (or at least a `4.2.0.4` tag in Docker Hub to be released) in the next couple of days?

**Comment by volmarl** [comment]
Yes this will be released today.

**Comment by volmarl** [comment]
Tags have now been updated on Docker Hub.

https://hub.docker.com/r/aerospike/aerospike-server/

**Comment by bmcstdio** [comment]
Thanks @volmarl!

**Pull request closed without merging**
